name: Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  test-and-lint:
    name: Test and lint
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout code
        uses: zendesk/checkout@v2

      - name: Set up Ruby
        uses: zendesk/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: "3.2"

      - name: Test and Lint
        run: |
          bundle install
          bundle exec rake
          bundle exec rubocop
